// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrTXqleFReliZlMsheG9Q7nRRngs7KhKw',
    appId: '1:561567872018:web:eba8bd9a2a35a59b0514cb',
    messagingSenderId: '561567872018',
    projectId: 'ticktree-dev',
    authDomain: 'ticktree-dev.firebaseapp.com',
    storageBucket: 'ticktree-dev.appspot.com',
    measurementId: 'G-T439EHZ40X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1PJywQkLiey0uGUNsvOumsJAqYHw0Wyo',
    appId: '1:561567872018:android:3ac53875435f83010514cb',
    messagingSenderId: '561567872018',
    projectId: 'ticktree-dev',
    storageBucket: 'ticktree-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0ozkJtZC2Uvpl0GkBjtZtrKO5neYKHrg',
    appId: '1:561567872018:ios:7e46dd0dd8512a660514cb',
    messagingSenderId: '561567872018',
    projectId: 'ticktree-dev',
    storageBucket: 'ticktree-dev.appspot.com',
    iosClientId: '561567872018-pirnqlvvig8576apnut57f74om54r6jn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticketTreeClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0ozkJtZC2Uvpl0GkBjtZtrKO5neYKHrg',
    appId: '1:561567872018:ios:7b9c760fba7d56750514cb',
    messagingSenderId: '561567872018',
    projectId: 'ticktree-dev',
    storageBucket: 'ticktree-dev.appspot.com',
    iosClientId: '561567872018-fj7ps2ido0q1q1urfuvqm80h9du5v180.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticketTreeClient.RunnerTests',
  );
}
